# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
services:
  - type: web
    plan: free
    name: node-app
    runtime: node
    repo: https://github.com/ErazorWhite/twitter-mock-api
    buildCommand: "npm install"
    startCommand: "npm start"
